version: 2
jobs:
  build-and-test:
    working_directory: /scifio-imageio-build
    docker:
      - image: insighttoolkit/module-ci:latest
    steps:
      - checkout:
          path: /scifio-imageio
      - run:
          name: Dependencies
          command: |
             apk --update add openjdk8-jre
      - run:
          name: Fetch CTest driver script
          command: |
            curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITK/dashboard/itk_common.cmake -O
      - run:
          name: Configure CTest script
          command: |
            SHASNIP=$(echo $CIRCLE_SHA1 | cut -c1-7)
            cat > dashboard.cmake << EOF
            set(CTEST_SITE "CircleCI")
            set(CTEST_BUILD_NAME "External-scifio-imageio-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}-${SHASNIP}")
            set(CTEST_BUILD_CONFIGURATION "MinSizeRel")
            set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
            set(CTEST_BUILD_FLAGS: "-j5")
            set(CTEST_SOURCE_DIRECTORY /scifio-imageio)
            set(CTEST_BINARY_DIRECTORY /scifio-imageio-build)
            set(dashboard_model Experimental)
            set(dashboard_no_clean 1)
            set(dashboard_cache "
            ITK_DIR:PATH=/ITK-build
            BUILD_TESTING:BOOL=ON
            ")
            include(\${CTEST_SCRIPT_DIRECTORY}/itk_common.cmake)
            EOF
      - run:
          name: Build and Test
          no_output_timeout: 1.0h
          command: |
            export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:/bin/java::")
            ctest -j 2 -VV -S dashboard.cmake

workflows:
    version: 2
    build-test-package:
      jobs:
        - build-and-test
